### PR TITLE
Fix [-Wformat-extra-args] build warnings

### PR DESCRIPTION
**Pull request by remicollet**
Tested with GCC 4.4, 4.8, 7.1 and 8.0
See https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html

### CODE REVIEW

**Comment by weltling** [comment]
This syntax seems to be supported by VC++ as well, so everything should be good.

Thanks.

**Comment by m6w6** [comment]
Sorry, this takes so long. I actually have a better fix locally, along with some other fixes.

Just out of curiosity, do we even have a working Windows build?

**Comment by weltling** [comment]
There used to be one. I've just triggered a snapshot build, lets see :)

Thanks.

**Comment by weltling** [comment]
Nope, failing https://windows.php.net/downloads/pecl/snaps/http/3.2.1dev/logs/. But seems another ext is causing it, raphf.

Thanks.

**Comment by m6w6** [comment]
Not sure, though, how [this](https://github.com/m6w6/ext-raphf/blob/master/config.w32) is different from others.

**Pull request closed without merging**
